### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Saif-Shines**

### CODE REVIEW

**Comment by hemchander23** [comment]
@Saif-Shines Thanks for adding the README! I've added my review comments. Could you work on them and push the changes to the feature branch in which you were working on?

**Comment by Saif-Shines** [comment]
I don't see review comments in this thread. Am I looking in the wrong place?

**Comment by hemchander23** [comment]
Looks good. 👍🏻Thanks!

**Comment by hemchander23** [comment]
+ Added contribution message before merge.

**Pull request merged**
